# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class LocalStorageStub(object):
    """Local storage service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVolume = channel.unary_unary(
                '/api.LocalStorage/CreateVolume',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageReply.FromString,
                )
        self.CreateSnapshot = channel.unary_unary(
                '/api.LocalStorage/CreateSnapshot',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageReply.FromString,
                )
        self.DeleteVolume = channel.unary_unary(
                '/api.LocalStorage/DeleteVolume',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageReply.FromString,
                )
        self.DeleteSnapshot = channel.unary_unary(
                '/api.LocalStorage/DeleteSnapshot',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageReply.FromString,
                )
        self.ResizeVolume = channel.unary_unary(
                '/api.LocalStorage/ResizeVolume',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageReply.FromString,
                )
        self.ListVolumes = channel.unary_unary(
                '/api.LocalStorage/ListVolumes',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageListReply.FromString,
                )
        self.ListDevices = channel.unary_unary(
                '/api.LocalStorage/ListDevices',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageListReply.FromString,
                )
        self.ListSnapshots = channel.unary_unary(
                '/api.LocalStorage/ListSnapshots',
                request_serializer=api__pb2.StorageRequest.SerializeToString,
                response_deserializer=api__pb2.StorageListReply.FromString,
                )


class LocalStorageServicer(object):
    """Local storage service definition.
    """

    def CreateVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVolumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVolume,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageReply.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageReply.SerializeToString,
            ),
            'DeleteVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVolume,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageReply.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageReply.SerializeToString,
            ),
            'ResizeVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeVolume,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageReply.SerializeToString,
            ),
            'ListVolumes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVolumes,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageListReply.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageListReply.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=api__pb2.StorageRequest.FromString,
                    response_serializer=api__pb2.StorageListReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.LocalStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocalStorage(object):
    """Local storage service definition.
    """

    @staticmethod
    def CreateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/CreateVolume',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/CreateSnapshot',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/DeleteVolume',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/DeleteSnapshot',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResizeVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/ResizeVolume',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVolumes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/ListVolumes',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/ListDevices',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.LocalStorage/ListSnapshots',
            api__pb2.StorageRequest.SerializeToString,
            api__pb2.StorageListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
