# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"N\n\x0eStorageRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65vices\x18\x03 \x03(\t\x12\x0c\n\x04size\x18\x04 \x01(\t\"4\n\x0cStorageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0breturn_code\x18\x02 \x01(\x03\"M\n\x10StorageListReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_json\x18\x02 \x01(\t\x12\x13\n\x0breturn_code\x18\x03 \x01(\x03\x32\xe1\x03\n\x0cLocalStorage\x12\x38\n\x0c\x43reateVolume\x12\x13.api.StorageRequest\x1a\x11.api.StorageReply\"\x00\x12:\n\x0e\x43reateSnapshot\x12\x13.api.StorageRequest\x1a\x11.api.StorageReply\"\x00\x12\x36\n\x0c\x44\x65leteVolume\x12\x13.api.StorageRequest\x1a\x11.api.StorageReply\x12\x38\n\x0e\x44\x65leteSnapshot\x12\x13.api.StorageRequest\x1a\x11.api.StorageReply\x12\x36\n\x0cResizeVolume\x12\x13.api.StorageRequest\x1a\x11.api.StorageReply\x12\x39\n\x0bListVolumes\x12\x13.api.StorageRequest\x1a\x15.api.StorageListReply\x12\x39\n\x0bListDevices\x12\x13.api.StorageRequest\x1a\x15.api.StorageListReply\x12;\n\rListSnapshots\x12\x13.api.StorageRequest\x1a\x15.api.StorageListReplyB\rZ\x0bstorage/apib\x06proto3')



_STORAGEREQUEST = DESCRIPTOR.message_types_by_name['StorageRequest']
_STORAGEREPLY = DESCRIPTOR.message_types_by_name['StorageReply']
_STORAGELISTREPLY = DESCRIPTOR.message_types_by_name['StorageListReply']
StorageRequest = _reflection.GeneratedProtocolMessageType('StorageRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StorageRequest)
  })
_sym_db.RegisterMessage(StorageRequest)

StorageReply = _reflection.GeneratedProtocolMessageType('StorageReply', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREPLY,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StorageReply)
  })
_sym_db.RegisterMessage(StorageReply)

StorageListReply = _reflection.GeneratedProtocolMessageType('StorageListReply', (_message.Message,), {
  'DESCRIPTOR' : _STORAGELISTREPLY,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StorageListReply)
  })
_sym_db.RegisterMessage(StorageListReply)

_LOCALSTORAGE = DESCRIPTOR.services_by_name['LocalStorage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013storage/api'
  _STORAGEREQUEST._serialized_start=18
  _STORAGEREQUEST._serialized_end=96
  _STORAGEREPLY._serialized_start=98
  _STORAGEREPLY._serialized_end=150
  _STORAGELISTREPLY._serialized_start=152
  _STORAGELISTREPLY._serialized_end=229
  _LOCALSTORAGE._serialized_start=232
  _LOCALSTORAGE._serialized_end=713
# @@protoc_insertion_point(module_scope)
