apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: springfield.csi.redhat.com
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: File 
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
