apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: springfield-csi-lvm
  annotations:
  labels:
    helm.sh/chart: springfield-0.1
    app.kubernetes.io/name: springfield
    app.kubernetes.io/instance: springfield
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/managed-by: Helm
provisioner: springfield.csi.redhat.com
parameters:
  fstype: xfs
  disks: /dev/XXXX,/dev/XXXX
  blivettype: DEVICE_TYPE_LVM
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
